### ISSUE TITLE
Relative Tile Paths in Catalog Files

### ISSUE THREAD

**Issue by nathanhilbert** [granularag/pyspatial#19]
I've moved over to pyspatial after the 10 minute queries that I was experiencing with postgis rasters, and it has worked out well.  I am having a slight annoyance with tile paths in the catalog json file.  It seems like the path is relative to the python code, not the json file as I expected.  I've been using absolute paths with the theory that code can move around, but data is relatively static; however moving from my local to dev to production forces me to regenerate the catalog file or edit the catalog paths as the case is.  That's fine, but I did hit a case when a shared folder might be mounted to multiple machines at different mount points and trying to read_catalog.  Do you have any thoughts on how I could approach this?

My opinion is that the path variable should be expanded to absolute relative to the json file in the [read_catalog function](https://github.com/granularag/pyspatial/blob/master/pyspatial/raster.py#L990).  I'm happy to submit a PR if this seems like a good solution from your end.  Thank you.

**Comment by aman-thakral** [comment]
I believe the path should be relative to the working directory of python.  Although, changing this to the json file sounds reasonable.  Could you provide an example for your use case? We could either make the json file be the new default behavior, or provide a simple optional argument:

```
def read_catalog(dataset_catalog_file, workdir=None):
    ...
    if workdir is None:
        path = decoded["Path"]
    else:
        path = os.path.join(workdir, decoded["Path"])
    ....
```

You could then parametrize the working directory in config files between dev/prod.

Glad to hear pyspatial has been working well for you. PRs are always welcome!

**Comment by nathanhilbert** [comment]
That's easy enough, and a good non-breaking solution.  I'll try it out, write a test, and submit a PR.
Thanks.

**Comment by nathanhilbert** [comment]
See this [example](https://gist.github.com/nathanhilbert/a91da1a4923e72d05d8a56a9a0ee3158) before suggested fix.

**Comment by nathanhilbert** [comment]
Closed with https://github.com/granularag/pyspatial/pull/21
