### ISSUE TITLE
Mixing fiona, shapely, & osgeo.gdal is not recommended

### ISSUE THREAD

**Issue by sgillies** [granularag/pyspatial#22]
Hi there, I notice in this project's `requirements.txt` both `fiona, shapely` and `GDAL`. Fiona and `osgeo.gdal/ogr` are not compatible, for reasons described at http://mapbox.github.io/rasterio/switch.html#mutual-incompatibility, and combining these packages in a Python program is a potential source of errors that will be difficult to debug.

**Comment by aman-thakral** [comment]
Thanks for the heads up. The link you provided seems to be for rasterio.  Is there similar documentation for fiona? Right now the use of fiona is limited to writing shapefiles only, and the import only occurs within the write_shapefile method.

**Comment by sgillies** [comment]
No, I haven't yet written anything for Fiona, but it has the same issues. Don't get me wrong: I _like_ that you're using Fiona and Shapely, I've put a lot of work into those projects. But using them together with `osgeo.*` is like mixing `requests` and `urllib2`.
